# -*- coding: utf-8 -*-
"""
Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HxNgz5_UBrI-ONlZsTIbsSXxBovv0a_L


The German Traffic Sign Recognition Benchmark (GTSRB) is a real-world image dataset designed to evaluate how well machine learning models can recognize traffic signs from camera images. It contains more than 50,000 labeled images of German road signs belonging to 43 different classes, such as speed limits, warning signs, and mandatory actions, collected under varied conditions (different lighting, distances, and viewing angles). The dataset was originally created for a multi-class image classification competition at IJCNN 2011 and has since become a standard benchmark for testing convolutional neural networks on traffic sign recognition tasks.

In your lab, students will use GTSRB to train a CNN that takes a single traffic sign image as input and predicts which sign class it belongs to. This makes the task directly relevant to autonomous driving and advanced driver-assistance systems, where reliable automatic understanding of traffic signs is safety‑critical. Since the original dataset is quite large, for this lab we will use a reduced version of the dataset, containing 5 classes and 2210 images.

For this lab, you will need to implement 2 tasks. The first one will be to complete the train_test_split function, and the second one will be to implement your CNN model in def_build function. The point distribution for this task will be as follows:

1. Test #1: function train_test_split (2.5 points)
2. Test #2: Above 0.70 accuracy on hidden test case (2.5 points)
3. Test #3: Above 0.80 accuracy on hidden test case (2.5 points)
4. Test #4: Above 0.95 accuracy on hidden test case (2.5 points)

## **Data Preparation**


1. Download the dataset from [here](https://course.cse.ust.hk/comp2211/labs/lab8/files/lab8_Fall2025_train.zip).
2. Upload this data to your Google Drive, under folder `comp2211/lab8`.
3. Run the following code cell to mount Google Drive and unzip the data.

Note: If this lasts for more than three minutes, you may try deleting the previously unzipped folder on Google Drive and try again.
"""

if __name__ == "__main__":
  from google.colab import drive
  import subprocess
  import os
  drive.mount("/content/drive")
  # Change working directory
  os.chdir("/content/drive/MyDrive/comp2211/lab8/")

  # Unzip the file 'lab8_Fall2025_train.zip' into the current directory
  zip_path = "lab8_train.zip"
  subprocess.run(["unzip", "-q", "-o", zip_path, "-d", "."], check=True)

"""## **Dataset Construction**

First, we prepare the dataset for visualization and CNN model from our image directory.  
"""

from PIL import Image
def prepare_dataset(directory):
    import os
    import numpy as np

    data = []
    labels = []
    classes = 5

    cur_path = directory

    for i in range(classes):
        path = os.path.join(cur_path, "Train", str(i))
        images = os.listdir(path)

        for a in images:
            try:
                image = Image.open(path + '/' + a)
                image = image.resize((30, 30))
                image = np.array(image)
                data.append(image)
                labels.append(i)

            except:
                print(f"Error loading image: {a}")

    data = np.array(data)
    labels = np.array(labels)

    return data,labels

if __name__ == "__main__":

    directory = os.getcwd()
    data, labels = prepare_dataset(directory)
    print(f"Data shape: {data[0].shape} \nTotal images: {labels.shape}")

import random
import matplotlib.pyplot as plt

plt.figure(figsize=(10, 10))

for i in range(5):
    for j in range(5):
        plt.subplot(5, 5, i * 5 + j + 1)
        plt.tight_layout()

        directory = os.getcwd()
        path = os.path.join(directory, "Train", str(i))

        random_image = random.choice(os.listdir(path))
        img = Image.open(os.path.join(path, random_image))

        plt.imshow(img)
        plt.title(f"Class: {i}")
        plt.axis('off')

plt.show()

"""## **Data Preparation**

### **Data Normalization & Train-validation split**

Before your CNN can learn traffic sign patterns, the raw dataset needs two critical preprocessing steps:

1. Train-Test Split: Prevents data leakage and enables proper model evaluation
2. Normalization: Ensures stable, fast training by scaling pixel values properly

If you train AND test on the same data, you'll get unrealistically perfect scores (100% accuracy!). Real-world models must predict unseen examples.

Also, Raw pixels range from [0, 255] (int8). Neural networks expect normalized inputs in [0, 1] (float32).

## **Task 1: Data Split**

For this task, you will split the dataset into 75% training dataset and 25% validation set. Data normalization and one-hot encoding have already been done for you.

You may consider using one of the following utilities for the split:

- `sklearn.model_selection.train_test_split`
- `keras.utils.split_dataset`
"""

def train_test_split(directory):

    '''
    Task 1: you need to split the full dataset into training and validation sets.
    It is crucial to have a separate validation set from the training set,
    as you will need to evaluate each new model using the validation set.
    Evaluating on the test set is not advisable, as it can lead to cherry-picking results.
    For instance, you might select different random seeds and choose the one that
    yields the highest accuracy on the test set. However, this approach does not
    contribute to developing better models, and we should avoid such practices.
    '''

    '''
    Split the dataset into training data (X_train, y_train) and validation data (X_val, y_val). We expect 1650 images
    to be used for training and 550 for validation.
    '''

    X_data, y_labels = prepare_dataset(directory)

    X_data = X_data.astype('float32')/255.0
    y_labels = y_labels

    X_train = None
    X_val = None
    y_train = None
    y_val = None

    # Task 1: Your code here

    import numpy as np

    np.random.seed(1)

    indices = np.arange(X_data.shape[0])
    np.random.shuffle(indices)
    val_indices = indices[:550]
    train_indices = indices[550:]

    X_train, X_val = X_data[train_indices], X_data[val_indices]
    y_train, y_val = y_labels[train_indices], y_labels[val_indices]
    # End Task

    # One-Hot Encoding for the labels
    from keras.utils import to_categorical

    y_train = to_categorical(y_train, 5)
    y_val = to_categorical(y_val, 5)

    return X_train, X_val, y_train, y_val

if __name__ == "__main__":

    X_train, X_val, y_train, y_val = train_test_split(directory)
    print(f"Final Training shape: {X_train.shape}")
    print(f"Final Validation shape: {X_val.shape}")

"""## **Task 2: Build the Model**

For this task, you will need to build a CNN model to predict the class each image belongs
to. The model shall output an array equivalent of length 5, where each value
corresponds to the possibility of the image belongs to each class. Your model shall
consist of at least one Conv2D layer and at least one Dense layer. Use activation
functions as appropriate and pay special attention to the last layer's activation.

For your reference, our model has only around 50,000 parameters. In our model,
we used the following layers:

Conv2D https://www.tensorflow.org/api_docs/python/tf/keras/layers/Conv2D

Dropout https://www.tensorflow.org/api_docs/python/tf/keras/layers/Dropout

MaxPooling2D https://www.tensorflow.org/api_docs/python/tf/keras/layers/MaxPool2D

Dense https://www.tensorflow.org/api_docs/python/tf/keras/layers/Dense

Feel free to explore other layers in tensorflow package if you want. Please
do not come up with a very large model with very large number of parameters, although
your marks will not be deducted as long as it can pass the test on ZINC

You will be scored on our own private test case. To achieve maximum score, you must score an accuracy above 0.95. We know it seems high, but do not worry! As long as your validation accuracy is high enough (> 96%), you will be able to pass the test.
"""

def build_model():

    '''
    Task 2: Build your CNN model here
    '''

    import tensorflow as tf
    from keras.models import Sequential
    from keras.layers import Conv2D, MaxPool2D, Dense, Flatten, Dropout, BatchNormalization
    model = Sequential()

    # Task 2: Your code here
    #第一层
    model.add(Conv2D(filters=32, kernel_size=(3, 3), activation='relu', input_shape=(30, 30, 3)))
    model.add(BatchNormalization())
    model.add(MaxPool2D(pool_size=(2, 2)))
    model.add(Dropout(rate=0.25))

    #第二层
    model.add(Conv2D(filters=64, kernel_size=(3, 3), activation='relu'))
    model.add(BatchNormalization())
    model.add(MaxPool2D(pool_size=(2, 2)))
    model.add(Dropout(rate=0.25))

    model.add(Flatten())
    model.add(Dense(256, activation='relu'))
    model.add(BatchNormalization())
    model.add(Dropout(rate=0.5))

    model.add(Dense(5, activation='softmax'))#5是num_classes

    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    # End Task

    return model

if __name__ == "__main__":
    model = build_model()
    model.compile(
        optimizer = "adam",
        loss = "categorical_crossentropy",
        metrics = ["accuracy"]
    )

    model.summary()

if __name__ == "__main__":

    from keras.callbacks import ModelCheckpoint

    # Train the model
    checkpoint = ModelCheckpoint(
    filepath='model_lab8.keras',
    monitor='val_accuracy',
    mode='max',
    save_best_only=True)
    history=model.fit(X_train, y_train,validation_data=(X_val, y_val), epochs=30,callbacks=[checkpoint])

"""## **Training log visualization**"""

if __name__ == "__main__":
    '''
    Now you can visualize model training loss and accuracy with the code below.
    '''
    import matplotlib.pyplot as plt
    plt.figure(figsize=(12, 5))

    plt.subplot(1, 2, 1)
    plt.plot(history.history['loss'], label='Train Loss')
    plt.plot(history.history['val_loss'], label='Validation Loss')
    plt.title('Model Loss')
    plt.ylabel('Loss')
    plt.xlabel('Epoch')
    plt.legend()

if __name__ == "__main__":
    plt.figure(figsize=(12, 5))
    plt.subplot(1, 2, 1)
    plt.plot(history.history['accuracy'], label='Train accuracy')
    plt.plot(history.history['val_accuracy'], label='Validation accuracy')
    plt.title('Model Accuracy')
    plt.ylabel('Accuracy')
    plt.xlabel('Epoch')
    plt.legend()

"""## **Evaluate the Model**

Make sure you are able to run the model properly. Otherwise, it might affect your score.
"""

from keras.models import load_model

if __name__ == "__main__":
    model = load_model('model_lab8.keras')          # Restore the best model
    val_loss, val_acc = model.evaluate(X_val, y_val)
    print('Validation loss: {}'.format(val_loss))
    print('Validation accuracy: {}'.format(val_acc))

